name: Bug Report
description: Report a bug or regression.
title: "bug: "
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Quick summary of the issue.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Step-by-step reproduction instructions.
      placeholder: |
        1. Go to ...
        2. Click on ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / screenshots
  - type: dropdown
    id: browsers
    attributes:
      label: Browsers
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
  - type: input
    id: version
    attributes:
      label: App version or commit
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any relevant console/server logs.
