name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Prisma generate
        run: pnpm prisma generate
      - name: Typecheck
        run: pnpm typecheck
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
      - name: Build
        run: pnpm build
      - name: Prisma validate
        run: pnpm prisma validate
      - name: Prisma migrate deploy (dry-run)
        run: pnpm prisma migrate deploy --preview-feature
      - name: Summary
        if: always()
        run: |
          echo "CI completed" >> $GITHUB_STEP_SUMMARY
