name: Preview Comment

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  comment:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create preview comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const summary = `🚀 Preview ready\n- Build status: ${context.payload.workflow_run.conclusion}\n- Preview URL: ${{ github.event.workflow_run.head_repository.html_url }}/deployments`; 
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.workflow_run.pull_requests[0].number,
              body: summary
            });
